cask_args appdir: '/Applications'

cask '1password'
cask 'appcleaner'
cask 'avocode'
cask 'bettertouchtool'
cask 'cleanmymac'
cask 'cloudapp'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'franz'
cask 'google-chrome'
cask 'imageoptim'
cask 'insomnia'
cask 'keepassx'
cask 'nordvpn'
cask 'notion'
cask 'overkill'
cask 'phpstorm'
cask 'sequel-pro'
cask 'sketch'
cask 'sourcetree'
cask 'spotify'
cask 'sublime-text'
cask 'vlc'
cask 'zeplin'